#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &

# Import theme settings
${SCRIPTSDIR}/import-gsettings.sh &

# Allow running apps as root
xhost si:localuser:root

# set wallpaper
swww init &

#insync start &
#dropbox &
#telegram-desktop &
discord --start-minimized &
steam-native -silent &
swayosd-server &
ydotoold &
# xwaylandvideobridge &
nm-applet --indicator &
/usr/lib/kdeconnectd &
kdeconnect-indicator &
#variety &
