#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts


# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Import theme settings
${SCRIPTSDIR}/import-gsettings.sh &

# Allow running apps as root
xhost si:localuser:root

# set wallpaper
swww-daemon &

wal -R &
hypridle &
waybar &
swaync &
swayosd-server &
nm-applet --indicator &

wl-clip-persist --clipboard regular &
ydotoold &
/usr/lib/kdeconnectd &
kdeconnect-indicator &
emote &
$HOME/.local/bin/wakapi --config $HOME/.config/wakapi.yml &

discord --start-minimized &
steam -silent -vgui &
OLLAMA_ORIGINS='*' OLLAMA_HOST='0.0.0.0' ollama serve &

sleep 2
swww restore &
