# ~/.config/starship.toml

# Use custom format
format = """
[┌────────>](bold cyan) $username in $hostname in $directory $python[|](bold cyan) $cmd_duration
[└─>](bold cyan) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_length = -1
# truncate_to_repo = false


[hostname]
style = "bold cyan"
ssh_only = false
disabled = false
format = "[$hostname]($style)"

[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)"

[cmd_duration]
min_time = 1
disabled = false
format = "[took $duration](italic green)"

[python]
style = "cyan"
format = '[(\($virtualenv\) )]($style) '
