-- Set up lspconfig.
-- local capabilities = require('cmp_nvim_lsp').default_capabilities()
-- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
-- require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
--   capabilities = capabilities
-- }

-- Autocommands (https://neovim.io/doc/user/autocmd.html)
-- vim.api.nvim_create_autocmd("BufEnter", {
--  pattern = { "*.json", "*.jsonc" },
--  -- enable wrap mode for json files only
--  command = "setlocal wrap",
-- })
-- vim.api.nvim_create_autocmd("FileType", {
--  pattern = "zsh",
--  callback = function()
--   -- let treesitter use bash highlight for zsh files as well
--   require("nvim-treesitter.highlight").attach(0, "bash")
--  end,
-- })
--
